micronaut:
  application:
    name: "spotify"

spotify:
  id: "caa2de5bb36d4e8fb6f942f3aa0d5c70"
  secret: "2362b802cea949798a8147083c06cab2"
  callback: "http://localhost:8080/callback"

redis:
  uri: redis://localhost:6379